/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.3/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "mafia-server"

include("mafia-game")
include("mafia-data")
include("mafia-lobby")
include("mafia-match")
include("mafia-web")
include("mafia-admin")
