### USER_CREATE
POST http://localhost:8080/rpc
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYWNjb3VudElkIjoxLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiZXhwIjoxNzU4OTAyOTE0fQ.-lhq2hLLodwUFgKOORAVIoNA89jp-1RMJFT3ITtYxzyu6pfvC8M4YGOx02RQNSHJ32uh2FT3Gi_pMDXhDAVZIQ

{
  "command": "USER_CREATE",
  "userCreateReq": {
    "nickname": "testnick"
  }
}