spring:
  datasource:
    game:
      url: jdbc:h2:mem:game
      username: sa
      password:
      enabled: true

    log:
      url: jdbc:h2:mem:log
      username: sa
      password:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    open-in-view: false

  h2:
    console:
      enabled: false

jwt:
  secret_key: d606a53ae647793f00d9e72598d28457dc9c51ad1f84e33dcb74233531515b11


logging:
  level:
    mafia.server: trace
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    game:
      url: jdbc:mysql://${DB_GAME_URL:localhost:3306}/game
      username: ${DB_GAME_USERNAME:root}
      password: ${DB_GAME_PASSWORD:1234}
      enabled: true

    log:
      url: jdbc:mysql://${DB_LOG_URL:localhost:3306}/log
      username: ${DB_LOG_USERNAME:root}
      password: ${DB_LOG_PASSWORD:1234}
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 50
    open-in-view: false

logging:
  level:
    mafia.server: debug

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    game:
      url: jdbc:mysql://${DB_GAME_URL:localhost:3306}/game
      username: ${DB_GAME_USERNAME:root}
      password: ${DB_GAME_PASSWORD:1234}
      enabled: true

    log:
      url: jdbc:mysql://${DB_LOG_URL:localhost:3306}/log
      username: ${DB_LOG_USERNAME:root}
      password: ${DB_LOG_PASSWORD:1234}
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 50
    open-in-view: false

logging:
  level:
    mafia.server: info