spring:
  datasource:
    account:
      url: jdbc:h2:mem:account
      username: sa
      password:
      enabled: true

    admin:
      url: jdbc:h2:mem:admin
      username: sa
      password:
      enabled: true

    game:
      url: jdbc:h2:mem:game
      username: sa
      password:
      enabled: true

    log:
      url: jdbc:h2:mem:log
      username: sa
      password:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    open-in-view: false

  h2:
    console:
      enabled: true

  data:
    redis:
      token:
        host: localhost
        port: 6379
        database: 0
        enabled: true

      game:
        host: localhost
        port: 6379
        database: 1
        enabled: true
