// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: web_protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from web_protocol.proto</summary>
public static partial class WebProtocolReflection {

  #region Descriptor
  /// <summary>File descriptor for web_protocol.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static WebProtocolReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJ3ZWJfcHJvdG9jb2wucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3Rh",
          "bXAucHJvdG8i1wEKB1JlcXVlc3QSIQoHY29tbWFuZBgBIAEoDjIQLlJlcXVl",
          "c3QuQ29tbWFuZBIMCgRsYW5nGAIgASgJEikKD3VzZXJfY3JlYXRlX3JlcRgK",
          "IAEoCzIOLlVzZXJDcmVhdGVSZXFIABIsChF1c2VyX2dldF9pbmZvX3JlcRgL",
          "IAEoCzIPLlVzZXJHZXRJbmZvUmVxSAAiOgoHQ29tbWFuZBILCgdVTktOT1dO",
          "EAASDwoLVVNFUl9DUkVBVEUQChIRCg1VU0VSX0dFVF9JTkZPEAtCBgoEYm9k",
          "eSIhCg1Vc2VyQ3JlYXRlUmVxEhAKCG5pY2tuYW1lGAEgASgJIhAKDlVzZXJH",
          "ZXRJbmZvUmVxIqECCghSZXNwb25zZRIhCgdjb21tYW5kGAEgASgOMhAuUmVx",
          "dWVzdC5Db21tYW5kEiAKBnJlc3VsdBgCIAEoDjIQLlJlc3BvbnNlLlJlc3Vs",
          "dBIPCgdtZXNzYWdlGAMgASgJEi0KCXRpbWVzdGFtcBgEIAEoCzIaLmdvb2ds",
          "ZS5wcm90b2J1Zi5UaW1lc3RhbXASKQoPdXNlcl9jcmVhdGVfcmVzGAogASgL",
          "Mg4uVXNlckNyZWF0ZVJlc0gAEiwKEXVzZXJfZ2V0X2luZm9fcmVzGAsgASgL",
          "Mg8uVXNlckdldEluZm9SZXNIACIvCgZSZXN1bHQSCwoHVU5LTk9XThAAEgsK",
          "B1NVQ0NFU1MQARILCgdGQUlMVVJFEAJCBgoEYm9keSK2AQoNVXNlckNyZWF0",
          "ZVJlcxI7ChJ1c2VyX2NyZWF0ZV9yZXN1bHQYASABKA4yHy5Vc2VyQ3JlYXRl",
          "UmVzLlVzZXJDcmVhdGVSZXN1bHQiaAoQVXNlckNyZWF0ZVJlc3VsdBILCgdV",
          "TktOT1dOEAASCwoHU1VDQ0VTUxABEg8KC0VYSVNUU19VU0VSEAISEwoPRVhJ",
          "U1RTX05JQ0tOQU1FEAMSFAoQSU5WQUxJRF9OSUNLTkFNRRAEIsIBCg5Vc2Vy",
          "R2V0SW5mb1JlcxI/ChR1c2VyX2dldF9pbmZvX3Jlc3VsdBgBIAEoDjIhLlVz",
          "ZXJHZXRJbmZvUmVzLlVzZXJHZXRJbmZvUmVzdWx0EhAKCG5pY2tuYW1lGAIg",
          "ASgJEg0KBWxldmVsGAMgASgFEgsKA2V4cBgEIAEoAyJBChFVc2VyR2V0SW5m",
          "b1Jlc3VsdBILCgdVTktOT1dOEAASCwoHU1VDQ0VTUxABEhIKDlVTRVJfTk9U",
          "X0ZPVU5EEAJCHwoQbWFmaWEuc2VydmVyLndlYkILV2ViUHJvdG9jb2xiBnBy",
          "b3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "Command", "Lang", "UserCreateReq", "UserGetInfoReq" }, new[]{ "Body" }, new[]{ typeof(global::Request.Types.Command) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UserCreateReq), global::UserCreateReq.Parser, new[]{ "Nickname" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UserGetInfoReq), global::UserGetInfoReq.Parser, null, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Response), global::Response.Parser, new[]{ "Command", "Result", "Message", "Timestamp", "UserCreateRes", "UserGetInfoRes" }, new[]{ "Body" }, new[]{ typeof(global::Response.Types.Result) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UserCreateRes), global::UserCreateRes.Parser, new[]{ "UserCreateResult" }, null, new[]{ typeof(global::UserCreateRes.Types.UserCreateResult) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UserGetInfoRes), global::UserGetInfoRes.Parser, new[]{ "UserGetInfoResult", "Nickname", "Level", "Exp" }, null, new[]{ typeof(global::UserGetInfoRes.Types.UserGetInfoResult) }, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Request : pb::IMessage<Request>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WebProtocolReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request(Request other) : this() {
    command_ = other.command_;
    lang_ = other.lang_;
    switch (other.BodyCase) {
      case BodyOneofCase.UserCreateReq:
        UserCreateReq = other.UserCreateReq.Clone();
        break;
      case BodyOneofCase.UserGetInfoReq:
        UserGetInfoReq = other.UserGetInfoReq.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "command" field.</summary>
  public const int CommandFieldNumber = 1;
  private global::Request.Types.Command command_ = global::Request.Types.Command.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Request.Types.Command Command {
    get { return command_; }
    set {
      command_ = value;
    }
  }

  /// <summary>Field number for the "lang" field.</summary>
  public const int LangFieldNumber = 2;
  private string lang_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Lang {
    get { return lang_; }
    set {
      lang_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "user_create_req" field.</summary>
  public const int UserCreateReqFieldNumber = 10;
  /// <summary>
  /// 10 ~ 19 유저 관련
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UserCreateReq UserCreateReq {
    get { return bodyCase_ == BodyOneofCase.UserCreateReq ? (global::UserCreateReq) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.UserCreateReq;
    }
  }

  /// <summary>Field number for the "user_get_info_req" field.</summary>
  public const int UserGetInfoReqFieldNumber = 11;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UserGetInfoReq UserGetInfoReq {
    get { return bodyCase_ == BodyOneofCase.UserGetInfoReq ? (global::UserGetInfoReq) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.UserGetInfoReq;
    }
  }

  private object body_;
  /// <summary>Enum of possible cases for the "body" oneof.</summary>
  public enum BodyOneofCase {
    None = 0,
    UserCreateReq = 10,
    UserGetInfoReq = 11,
  }
  private BodyOneofCase bodyCase_ = BodyOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BodyOneofCase BodyCase {
    get { return bodyCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBody() {
    bodyCase_ = BodyOneofCase.None;
    body_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Command != other.Command) return false;
    if (Lang != other.Lang) return false;
    if (!object.Equals(UserCreateReq, other.UserCreateReq)) return false;
    if (!object.Equals(UserGetInfoReq, other.UserGetInfoReq)) return false;
    if (BodyCase != other.BodyCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Command != global::Request.Types.Command.Unknown) hash ^= Command.GetHashCode();
    if (Lang.Length != 0) hash ^= Lang.GetHashCode();
    if (bodyCase_ == BodyOneofCase.UserCreateReq) hash ^= UserCreateReq.GetHashCode();
    if (bodyCase_ == BodyOneofCase.UserGetInfoReq) hash ^= UserGetInfoReq.GetHashCode();
    hash ^= (int) bodyCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Command != global::Request.Types.Command.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Command);
    }
    if (Lang.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Lang);
    }
    if (bodyCase_ == BodyOneofCase.UserCreateReq) {
      output.WriteRawTag(82);
      output.WriteMessage(UserCreateReq);
    }
    if (bodyCase_ == BodyOneofCase.UserGetInfoReq) {
      output.WriteRawTag(90);
      output.WriteMessage(UserGetInfoReq);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Command != global::Request.Types.Command.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Command);
    }
    if (Lang.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Lang);
    }
    if (bodyCase_ == BodyOneofCase.UserCreateReq) {
      output.WriteRawTag(82);
      output.WriteMessage(UserCreateReq);
    }
    if (bodyCase_ == BodyOneofCase.UserGetInfoReq) {
      output.WriteRawTag(90);
      output.WriteMessage(UserGetInfoReq);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Command != global::Request.Types.Command.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
    }
    if (Lang.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Lang);
    }
    if (bodyCase_ == BodyOneofCase.UserCreateReq) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserCreateReq);
    }
    if (bodyCase_ == BodyOneofCase.UserGetInfoReq) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserGetInfoReq);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.Command != global::Request.Types.Command.Unknown) {
      Command = other.Command;
    }
    if (other.Lang.Length != 0) {
      Lang = other.Lang;
    }
    switch (other.BodyCase) {
      case BodyOneofCase.UserCreateReq:
        if (UserCreateReq == null) {
          UserCreateReq = new global::UserCreateReq();
        }
        UserCreateReq.MergeFrom(other.UserCreateReq);
        break;
      case BodyOneofCase.UserGetInfoReq:
        if (UserGetInfoReq == null) {
          UserGetInfoReq = new global::UserGetInfoReq();
        }
        UserGetInfoReq.MergeFrom(other.UserGetInfoReq);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Command = (global::Request.Types.Command) input.ReadEnum();
          break;
        }
        case 18: {
          Lang = input.ReadString();
          break;
        }
        case 82: {
          global::UserCreateReq subBuilder = new global::UserCreateReq();
          if (bodyCase_ == BodyOneofCase.UserCreateReq) {
            subBuilder.MergeFrom(UserCreateReq);
          }
          input.ReadMessage(subBuilder);
          UserCreateReq = subBuilder;
          break;
        }
        case 90: {
          global::UserGetInfoReq subBuilder = new global::UserGetInfoReq();
          if (bodyCase_ == BodyOneofCase.UserGetInfoReq) {
            subBuilder.MergeFrom(UserGetInfoReq);
          }
          input.ReadMessage(subBuilder);
          UserGetInfoReq = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Command = (global::Request.Types.Command) input.ReadEnum();
          break;
        }
        case 18: {
          Lang = input.ReadString();
          break;
        }
        case 82: {
          global::UserCreateReq subBuilder = new global::UserCreateReq();
          if (bodyCase_ == BodyOneofCase.UserCreateReq) {
            subBuilder.MergeFrom(UserCreateReq);
          }
          input.ReadMessage(subBuilder);
          UserCreateReq = subBuilder;
          break;
        }
        case 90: {
          global::UserGetInfoReq subBuilder = new global::UserGetInfoReq();
          if (bodyCase_ == BodyOneofCase.UserGetInfoReq) {
            subBuilder.MergeFrom(UserGetInfoReq);
          }
          input.ReadMessage(subBuilder);
          UserGetInfoReq = subBuilder;
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Request message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Command {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      /// <summary>
      /// 10 ~ 19 유저 관련
      /// </summary>
      [pbr::OriginalName("USER_CREATE")] UserCreate = 10,
      [pbr::OriginalName("USER_GET_INFO")] UserGetInfo = 11,
    }

  }
  #endregion

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class UserCreateReq : pb::IMessage<UserCreateReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserCreateReq> _parser = new pb::MessageParser<UserCreateReq>(() => new UserCreateReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserCreateReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WebProtocolReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserCreateReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserCreateReq(UserCreateReq other) : this() {
    nickname_ = other.nickname_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserCreateReq Clone() {
    return new UserCreateReq(this);
  }

  /// <summary>Field number for the "nickname" field.</summary>
  public const int NicknameFieldNumber = 1;
  private string nickname_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Nickname {
    get { return nickname_; }
    set {
      nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserCreateReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserCreateReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Nickname != other.Nickname) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Nickname.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Nickname);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Nickname.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Nickname);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Nickname.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserCreateReq other) {
    if (other == null) {
      return;
    }
    if (other.Nickname.Length != 0) {
      Nickname = other.Nickname;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Nickname = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Nickname = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class UserGetInfoReq : pb::IMessage<UserGetInfoReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserGetInfoReq> _parser = new pb::MessageParser<UserGetInfoReq>(() => new UserGetInfoReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserGetInfoReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WebProtocolReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserGetInfoReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserGetInfoReq(UserGetInfoReq other) : this() {
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserGetInfoReq Clone() {
    return new UserGetInfoReq(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserGetInfoReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserGetInfoReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserGetInfoReq other) {
    if (other == null) {
      return;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class Response : pb::IMessage<Response>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Response> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WebProtocolReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response(Response other) : this() {
    command_ = other.command_;
    result_ = other.result_;
    message_ = other.message_;
    timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
    switch (other.BodyCase) {
      case BodyOneofCase.UserCreateRes:
        UserCreateRes = other.UserCreateRes.Clone();
        break;
      case BodyOneofCase.UserGetInfoRes:
        UserGetInfoRes = other.UserGetInfoRes.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Response Clone() {
    return new Response(this);
  }

  /// <summary>Field number for the "command" field.</summary>
  public const int CommandFieldNumber = 1;
  private global::Request.Types.Command command_ = global::Request.Types.Command.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Request.Types.Command Command {
    get { return command_; }
    set {
      command_ = value;
    }
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 2;
  private global::Response.Types.Result result_ = global::Response.Types.Result.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Response.Types.Result Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 3;
  private string message_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 4;
  private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "user_create_res" field.</summary>
  public const int UserCreateResFieldNumber = 10;
  /// <summary>
  /// 10 ~ 19 유저 관련
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UserCreateRes UserCreateRes {
    get { return bodyCase_ == BodyOneofCase.UserCreateRes ? (global::UserCreateRes) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.UserCreateRes;
    }
  }

  /// <summary>Field number for the "user_get_info_res" field.</summary>
  public const int UserGetInfoResFieldNumber = 11;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UserGetInfoRes UserGetInfoRes {
    get { return bodyCase_ == BodyOneofCase.UserGetInfoRes ? (global::UserGetInfoRes) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.UserGetInfoRes;
    }
  }

  private object body_;
  /// <summary>Enum of possible cases for the "body" oneof.</summary>
  public enum BodyOneofCase {
    None = 0,
    UserCreateRes = 10,
    UserGetInfoRes = 11,
  }
  private BodyOneofCase bodyCase_ = BodyOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BodyOneofCase BodyCase {
    get { return bodyCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBody() {
    bodyCase_ = BodyOneofCase.None;
    body_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Response);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Response other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Command != other.Command) return false;
    if (Result != other.Result) return false;
    if (Message != other.Message) return false;
    if (!object.Equals(Timestamp, other.Timestamp)) return false;
    if (!object.Equals(UserCreateRes, other.UserCreateRes)) return false;
    if (!object.Equals(UserGetInfoRes, other.UserGetInfoRes)) return false;
    if (BodyCase != other.BodyCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Command != global::Request.Types.Command.Unknown) hash ^= Command.GetHashCode();
    if (Result != global::Response.Types.Result.Unknown) hash ^= Result.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
    if (bodyCase_ == BodyOneofCase.UserCreateRes) hash ^= UserCreateRes.GetHashCode();
    if (bodyCase_ == BodyOneofCase.UserGetInfoRes) hash ^= UserGetInfoRes.GetHashCode();
    hash ^= (int) bodyCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Command != global::Request.Types.Command.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Command);
    }
    if (Result != global::Response.Types.Result.Unknown) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Result);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Message);
    }
    if (timestamp_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Timestamp);
    }
    if (bodyCase_ == BodyOneofCase.UserCreateRes) {
      output.WriteRawTag(82);
      output.WriteMessage(UserCreateRes);
    }
    if (bodyCase_ == BodyOneofCase.UserGetInfoRes) {
      output.WriteRawTag(90);
      output.WriteMessage(UserGetInfoRes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Command != global::Request.Types.Command.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Command);
    }
    if (Result != global::Response.Types.Result.Unknown) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Result);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Message);
    }
    if (timestamp_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Timestamp);
    }
    if (bodyCase_ == BodyOneofCase.UserCreateRes) {
      output.WriteRawTag(82);
      output.WriteMessage(UserCreateRes);
    }
    if (bodyCase_ == BodyOneofCase.UserGetInfoRes) {
      output.WriteRawTag(90);
      output.WriteMessage(UserGetInfoRes);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Command != global::Request.Types.Command.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
    }
    if (Result != global::Response.Types.Result.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (timestamp_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
    }
    if (bodyCase_ == BodyOneofCase.UserCreateRes) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserCreateRes);
    }
    if (bodyCase_ == BodyOneofCase.UserGetInfoRes) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserGetInfoRes);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Response other) {
    if (other == null) {
      return;
    }
    if (other.Command != global::Request.Types.Command.Unknown) {
      Command = other.Command;
    }
    if (other.Result != global::Response.Types.Result.Unknown) {
      Result = other.Result;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    if (other.timestamp_ != null) {
      if (timestamp_ == null) {
        Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      Timestamp.MergeFrom(other.Timestamp);
    }
    switch (other.BodyCase) {
      case BodyOneofCase.UserCreateRes:
        if (UserCreateRes == null) {
          UserCreateRes = new global::UserCreateRes();
        }
        UserCreateRes.MergeFrom(other.UserCreateRes);
        break;
      case BodyOneofCase.UserGetInfoRes:
        if (UserGetInfoRes == null) {
          UserGetInfoRes = new global::UserGetInfoRes();
        }
        UserGetInfoRes.MergeFrom(other.UserGetInfoRes);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Command = (global::Request.Types.Command) input.ReadEnum();
          break;
        }
        case 16: {
          Result = (global::Response.Types.Result) input.ReadEnum();
          break;
        }
        case 26: {
          Message = input.ReadString();
          break;
        }
        case 34: {
          if (timestamp_ == null) {
            Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timestamp);
          break;
        }
        case 82: {
          global::UserCreateRes subBuilder = new global::UserCreateRes();
          if (bodyCase_ == BodyOneofCase.UserCreateRes) {
            subBuilder.MergeFrom(UserCreateRes);
          }
          input.ReadMessage(subBuilder);
          UserCreateRes = subBuilder;
          break;
        }
        case 90: {
          global::UserGetInfoRes subBuilder = new global::UserGetInfoRes();
          if (bodyCase_ == BodyOneofCase.UserGetInfoRes) {
            subBuilder.MergeFrom(UserGetInfoRes);
          }
          input.ReadMessage(subBuilder);
          UserGetInfoRes = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Command = (global::Request.Types.Command) input.ReadEnum();
          break;
        }
        case 16: {
          Result = (global::Response.Types.Result) input.ReadEnum();
          break;
        }
        case 26: {
          Message = input.ReadString();
          break;
        }
        case 34: {
          if (timestamp_ == null) {
            Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(Timestamp);
          break;
        }
        case 82: {
          global::UserCreateRes subBuilder = new global::UserCreateRes();
          if (bodyCase_ == BodyOneofCase.UserCreateRes) {
            subBuilder.MergeFrom(UserCreateRes);
          }
          input.ReadMessage(subBuilder);
          UserCreateRes = subBuilder;
          break;
        }
        case 90: {
          global::UserGetInfoRes subBuilder = new global::UserGetInfoRes();
          if (bodyCase_ == BodyOneofCase.UserGetInfoRes) {
            subBuilder.MergeFrom(UserGetInfoRes);
          }
          input.ReadMessage(subBuilder);
          UserGetInfoRes = subBuilder;
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the Response message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    /// <summary>
    /// 요청의 유효성에 대한 결과
    /// </summary>
    public enum Result {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      [pbr::OriginalName("SUCCESS")] Success = 1,
      [pbr::OriginalName("FAILURE")] Failure = 2,
    }

  }
  #endregion

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class UserCreateRes : pb::IMessage<UserCreateRes>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserCreateRes> _parser = new pb::MessageParser<UserCreateRes>(() => new UserCreateRes());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserCreateRes> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WebProtocolReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserCreateRes() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserCreateRes(UserCreateRes other) : this() {
    userCreateResult_ = other.userCreateResult_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserCreateRes Clone() {
    return new UserCreateRes(this);
  }

  /// <summary>Field number for the "user_create_result" field.</summary>
  public const int UserCreateResultFieldNumber = 1;
  private global::UserCreateRes.Types.UserCreateResult userCreateResult_ = global::UserCreateRes.Types.UserCreateResult.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UserCreateRes.Types.UserCreateResult UserCreateResult {
    get { return userCreateResult_; }
    set {
      userCreateResult_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserCreateRes);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserCreateRes other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserCreateResult != other.UserCreateResult) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UserCreateResult != global::UserCreateRes.Types.UserCreateResult.Unknown) hash ^= UserCreateResult.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UserCreateResult != global::UserCreateRes.Types.UserCreateResult.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) UserCreateResult);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UserCreateResult != global::UserCreateRes.Types.UserCreateResult.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) UserCreateResult);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UserCreateResult != global::UserCreateRes.Types.UserCreateResult.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UserCreateResult);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserCreateRes other) {
    if (other == null) {
      return;
    }
    if (other.UserCreateResult != global::UserCreateRes.Types.UserCreateResult.Unknown) {
      UserCreateResult = other.UserCreateResult;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          UserCreateResult = (global::UserCreateRes.Types.UserCreateResult) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          UserCreateResult = (global::UserCreateRes.Types.UserCreateResult) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the UserCreateRes message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum UserCreateResult {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      [pbr::OriginalName("SUCCESS")] Success = 1,
      /// <summary>
      /// 이미 해당 계정의 유저가 있는 경우
      /// </summary>
      [pbr::OriginalName("EXISTS_USER")] ExistsUser = 2,
      [pbr::OriginalName("EXISTS_NICKNAME")] ExistsNickname = 3,
      [pbr::OriginalName("INVALID_NICKNAME")] InvalidNickname = 4,
    }

  }
  #endregion

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class UserGetInfoRes : pb::IMessage<UserGetInfoRes>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserGetInfoRes> _parser = new pb::MessageParser<UserGetInfoRes>(() => new UserGetInfoRes());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserGetInfoRes> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::WebProtocolReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserGetInfoRes() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserGetInfoRes(UserGetInfoRes other) : this() {
    userGetInfoResult_ = other.userGetInfoResult_;
    nickname_ = other.nickname_;
    level_ = other.level_;
    exp_ = other.exp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserGetInfoRes Clone() {
    return new UserGetInfoRes(this);
  }

  /// <summary>Field number for the "user_get_info_result" field.</summary>
  public const int UserGetInfoResultFieldNumber = 1;
  private global::UserGetInfoRes.Types.UserGetInfoResult userGetInfoResult_ = global::UserGetInfoRes.Types.UserGetInfoResult.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::UserGetInfoRes.Types.UserGetInfoResult UserGetInfoResult {
    get { return userGetInfoResult_; }
    set {
      userGetInfoResult_ = value;
    }
  }

  /// <summary>Field number for the "nickname" field.</summary>
  public const int NicknameFieldNumber = 2;
  private string nickname_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Nickname {
    get { return nickname_; }
    set {
      nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "level" field.</summary>
  public const int LevelFieldNumber = 3;
  private int level_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Level {
    get { return level_; }
    set {
      level_ = value;
    }
  }

  /// <summary>Field number for the "exp" field.</summary>
  public const int ExpFieldNumber = 4;
  private long exp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Exp {
    get { return exp_; }
    set {
      exp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserGetInfoRes);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserGetInfoRes other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (UserGetInfoResult != other.UserGetInfoResult) return false;
    if (Nickname != other.Nickname) return false;
    if (Level != other.Level) return false;
    if (Exp != other.Exp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (UserGetInfoResult != global::UserGetInfoRes.Types.UserGetInfoResult.Unknown) hash ^= UserGetInfoResult.GetHashCode();
    if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
    if (Level != 0) hash ^= Level.GetHashCode();
    if (Exp != 0L) hash ^= Exp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (UserGetInfoResult != global::UserGetInfoRes.Types.UserGetInfoResult.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) UserGetInfoResult);
    }
    if (Nickname.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Nickname);
    }
    if (Level != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Level);
    }
    if (Exp != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Exp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (UserGetInfoResult != global::UserGetInfoRes.Types.UserGetInfoResult.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) UserGetInfoResult);
    }
    if (Nickname.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Nickname);
    }
    if (Level != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Level);
    }
    if (Exp != 0L) {
      output.WriteRawTag(32);
      output.WriteInt64(Exp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (UserGetInfoResult != global::UserGetInfoRes.Types.UserGetInfoResult.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UserGetInfoResult);
    }
    if (Nickname.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
    }
    if (Level != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
    }
    if (Exp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Exp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserGetInfoRes other) {
    if (other == null) {
      return;
    }
    if (other.UserGetInfoResult != global::UserGetInfoRes.Types.UserGetInfoResult.Unknown) {
      UserGetInfoResult = other.UserGetInfoResult;
    }
    if (other.Nickname.Length != 0) {
      Nickname = other.Nickname;
    }
    if (other.Level != 0) {
      Level = other.Level;
    }
    if (other.Exp != 0L) {
      Exp = other.Exp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          UserGetInfoResult = (global::UserGetInfoRes.Types.UserGetInfoResult) input.ReadEnum();
          break;
        }
        case 18: {
          Nickname = input.ReadString();
          break;
        }
        case 24: {
          Level = input.ReadInt32();
          break;
        }
        case 32: {
          Exp = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          UserGetInfoResult = (global::UserGetInfoRes.Types.UserGetInfoResult) input.ReadEnum();
          break;
        }
        case 18: {
          Nickname = input.ReadString();
          break;
        }
        case 24: {
          Level = input.ReadInt32();
          break;
        }
        case 32: {
          Exp = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the UserGetInfoRes message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum UserGetInfoResult {
      [pbr::OriginalName("UNKNOWN")] Unknown = 0,
      [pbr::OriginalName("SUCCESS")] Success = 1,
      /// <summary>
      /// USER_CREATE 요청 필요
      /// </summary>
      [pbr::OriginalName("USER_NOT_FOUND")] UserNotFound = 2,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
